-- Generated by scripts/build-incumbent-history.mjs — do not edit.
-- Incumbent's last Dem-minus-Rep margin where the same person runs again.
-- Source: Silver Bulletin rawpolls archive (results attached).

UPDATE races SET incumbent_last_margin = -8.6 WHERE id = 'sen-2026-ME'; -- susan m. collins 2020
UPDATE races SET incumbent_last_margin = -12.7 WHERE id = 'sen-2026-AK'; -- dan sullivan 2020
UPDATE races SET incumbent_last_margin = -10.3 WHERE id = 'sen-2026-SC'; -- lindsey graham 2020
UPDATE races SET incumbent_last_margin = -10.0 WHERE id = 'sen-2026-MS'; -- cindy hyde-smith 2020
UPDATE races SET incumbent_last_margin = -25.2 WHERE id = 'sen-2026-NE'; -- pete ricketts 2024
UPDATE races SET incumbent_last_margin = -27.0 WHERE id = 'sen-2026-TN'; -- bill hagerty 2020
UPDATE races SET incumbent_last_margin = -26.5 WHERE id = 'sen-2026-OK'; -- markwayne mullin 2022
UPDATE races SET incumbent_last_margin = -1.5 WHERE id = 'gov-2026-NV'; -- joe lombardo 2022
UPDATE races SET incumbent_last_margin = -9.4 WHERE id = 'gov-2026-NH'; -- kelly ayotte 2024
UPDATE races SET incumbent_last_margin = 0.7 WHERE id = 'gov-2026-AZ'; -- katie hobbs 2022
UPDATE races SET incumbent_last_margin = -10.9 WHERE id = 'gov-2026-TX'; -- greg abbott 2022
UPDATE races SET incumbent_last_margin = 3.4 WHERE id = 'gov-2026-OR'; -- tina kotek 2022
UPDATE races SET incumbent_last_margin = 14.8 WHERE id = 'gov-2026-PA'; -- josh shapiro 2024
UPDATE races SET incumbent_last_margin = 6.4 WHERE id = 'gov-2026-NY'; -- kathy c. hochul 2022
UPDATE races SET incumbent_last_margin = 12.8 WHERE id = 'gov-2026-CT'; -- edward lamont 2022
UPDATE races SET incumbent_last_margin = -27.8 WHERE id = 'gov-2026-AR'; -- sarah huckabee sanders 2022
UPDATE races SET incumbent_last_margin = -51.6 WHERE id = 'gov-2026-VT'; -- phil scott 2024
UPDATE races SET incumbent_last_margin = -21.6 WHERE id = 'gov-2026-ID'; -- brad little 2018
UPDATE races SET incumbent_last_margin = 29.1 WHERE id = 'gov-2026-MA'; -- maura healey 2022
UPDATE races SET incumbent_last_margin = -61.9 WHERE id = 'gov-2026-WY'; -- mark gordon 2022
